### ISSUE TITLE
Instructions for Permanent Extra Fields

### ISSUE THREAD

**Issue by kaitwalla** [vanilophp/cart#17]
Hi, I'm trying to use the instructions for the Permanent Extra Fields, but it references a config file (config/vanilo.php) that I don't have. I'm only using the Cart module, not the framework - is this not doable in that context?

**Comment by fulopattila122** [comment]
Hey, sorry for the late response. Yes, just add `vanilo.php` in your application's `config/` folder. It will work due to Laravel's handling of config files and "config namespaces".

**Comment by fulopattila122** [comment]
Feel free to reopen if further questions arise.
