### ISSUE TITLE
Configurable Table Name for Cart Model

### ISSUE THREAD

**Issue by adrienne** [vanilophp/cart#18]
Currently Vanilo assumes that the table name is `carts`, and there is no way to configure this. Can you make this a config setting, please? 

I'll try to submit a pull request.

**Comment by fulopattila122** [comment]
Hi Adrienne,

we have no plans to make the table names configurable, but you can easily achieve it in your project with <30 minutes of work.

Here's what to do:

1. [Disable the built-in migrations](https://konekt.dev/concord/1.x/migrations#turn-migrations-onoff) of the Cart module:
   config/concord.php:
   ```php
    'modules' => [
        Vanilo\Cart\Providers\ModuleServiceProvider::class => [
            'migrations' => false
        ]
    ]
   ```
2. [Publish the migrations](https://konekt.dev/concord/1.x/publishing#migrations):
   ```bash
   php artisan vendor:publish --provider="Vanilo\Cart\Providers\ModuleServiceProvider" --tag="migrations"
   ```
   This will copy the [Cart Module's migrations](https://github.com/vanilophp/cart/tree/master/resources/database/migrations) into your app's `database/` folder.
3. Modify the table names in those migrations. Now you can run `php artisan migrate`.
4. Create `Cart.php` and `CartItem.php` files in the `app/Models/` folder.
5. Add the following content to `Cart.php`:
   ```php
   class Cart extends Vanilo\Cart\Models\Cart
   {
       protected $table = 'your_cart_table_name';
   }
   ```
6. Add the following content to `CartItem.php`:
   ```php
   class CartItem extends Vanilo\Cart\Models\CartItem
   {
       protected $table = 'your_cart_items_table_name';
   }
   ```
7. Add these lines to `app/Providers/AppServiceProvider.php`:
   ```php
   namespace App\Providers;

   use Illuminate\Support\ServiceProvider;
   use Vanilo\Cart\Contracts\Cart as CartContract;
   use Vanilo\Cart\Contracts\CartItem as CartItemContract;

   class AppServiceProvider extends ServiceProvider
   {
       public function boot()
       {
           $this->app->concord->registerModel(CartContract::class, \App\Models\Cart::class);
           $this->app->concord->registerModel(CartItemContract::class, \App\Models\CartItem::class);
       }
   }
   ```

Now you can use the cart module with your custom table names.

### Notes

- You can continue using the `Cart` facade (it will use your models under the hood):
   ```php
   use Vanilo\Cart\Facades\Cart;
   
   Cart::addItem($product);
   // etc..
   ```
- These steps apply only when you're using the Cart module,
- If you're using the entire Vanilo Framework, then the config part is slightly different (let me know if that's the case)
- If you'll update the Cart module with composer in the future, make sure to take over the newer migrations by re-running the `php artisan vendor:publish --provider="Vanilo\Cart\Providers\ModuleServiceProvider" --tag="migrations"` command. If there are new migrations, change the table names in them accordingly.

### References & Further Info

- https://vanilo.io/docs/3.x/models
- https://vanilo.io/how-to/use-custom-models-in-your-application
- https://konekt.dev/concord/1.x/migrations#turn-migrations-onoff
- https://konekt.dev/concord/1.x/publishing#migrations
- https://laravel.com/docs/9.x/eloquent#table-names

**Comment by adrienne** [comment]
@fulopattila122 - this did work, thank you!
