### ISSUE TITLE
Resources not being published

### ISSUE THREAD

**Issue by danishjamil** [vanilophp/cart#3]
Hi

The migrations and config file is not published when running php artisan vendor:publish when only this package is being installed instead of whole framework.

**Comment by fulopattila122** [comment]
Did you install Concord before?

**Comment by fulopattila122** [comment]
Ok, I probably know what's wrong. Concord was installed along with the cart package, you just have to add the cart module to it. This part hasn't yet been added to docs (only to framework installation). I add this part shortly to the doc and will post it here as well.

**Comment by fulopattila122** [comment]
Thanks for the feedback, this was definitely incompletely documented.
I've updated the readme with installation instructions for standalone usage.

Basically what you need to do is to run these:

1. `php artisan vendor:publish --provider=Konekt\Concord\ConcordServiceProvider`
2. Add `Vanilo\Cart\Providers\ModuleServiceProvider::class` to modules in `config/concord.php`

Now the migrations are registered so you can run `php artisan migrate`.
