### ISSUE TITLE
How to Update cart item quantity

### ISSUE THREAD

**Issue by victorighalo** [vanilophp/cart#7]
So I've implemented using the cart library in my project but i can't seem to be able to update a cart item's quantity. How do I do that?

**Comment by fulopattila122** [comment]
How do you add an item to your cart?
How do you get the quantity from the cart?

**Comment by victorighalo** [comment]
> How do you add an item to your cart?
> How do you get the quantity from the cart?

There are static methods addItem() and itemCount(). The method getItems() returns a collection. I was expecting it to return a Model instance so i can run a where query on it and get the cart item then modify and save..

**Comment by victorighalo** [comment]
I got it to work, i used your example here 

https://github.com/vanilophp/demo/blob/0.5/app/Http/Controllers/CartController.php

Thanks.

**Comment by fulopattila122** [comment]
Check this to clarify the details: https://vanilo.io/docs/0.5/cart
