### ISSUE TITLE
Empty cart after page refresh. 

### ISSUE THREAD

**Issue by victorighalo** [vanilophp/cart#8]
I'm implementing a custom Buyable Model but after successfully adding to Cart, cart count returns the correct values but after page refresh cart count goes back to zero.

**Comment by fulopattila122** [comment]
Can you please post some code examples?

**Comment by victorighalo** [comment]
> Can you please post some code examples?

```php
use Illuminate\Http\Request;
use Vanilo\Cart\Facades\Cart;
use Vanilo\Cart\Contracts\CartItem;

//Add to Cart -- This works and returns quantity
$product = \App\Product::findBySlug($request->slug);
Cart::addItem($product, $request->qty);
return response()->json(['message' => 'Added to cart', 'cart_count' => Cart::itemCount()]);
 ```

```php
//Returns zero after refresh
if(Cart::exists()){
$cart_count = Cart::itemCount();
$cart = Cart::model()->items;
}else{
$cart_count = 0;
$cart = [];
}
return view('pages.front.cart', compact('cart', 'cart_count'));
```

```php

//Product model
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Vanilo\Contracts\Buyable;
use Vanilo\Product\Models\Product as BaseProduct;
use Vanilo\Support\Traits\BuyableModel;
use Vanilo\Support\Traits\BuyableImageSpatieV7;
use willvincent\Rateable\Rateable;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Vanilo\Category\Models\TaxonProxy;
use BrianFaust\Commentable\Traits\HasComments;

class Product extends BaseProduct implements Buyable, HasMedia
{
    use
        Rateable,
        BuyableModel,
        BuyableImageSpatieV7,
        HasComments,
        HasMediaTrait;

    public function taxons(): MorphToMany
    {
        return $this->morphToMany(
            TaxonProxy::modelClass(), 'model', 'model_taxons', 'model_id', 'taxon_id'
        );
    }
}
```

**Comment by fulopattila122** [comment]
Can you please also include the `use Class\Name` section as well?

**Comment by victorighalo** [comment]
> Can you please also include the `use Class\Name` section as well?

I've updated the code example

**Comment by fulopattila122** [comment]
Few tips:
1. You can use the [HasTaxons](https://github.com/vanilophp/category/blob/master/src/Traits/HasTaxons.php) trait on your product model.
2. You don't have to check whether the cart exists for the count, [it's being done internally](https://github.com/vanilophp/cart/blob/master/src/CartManager.php#L87).
3. Don't access the `Cart::model()` directly unless you really, really, really (really?) need it. Use `Cart::getItems()` instead.

```php
return view('pages.front.cart', ['cart' => Cart::getItems(), 'cart_count' => Cart::itemCount()]);
```

Regarding the bug: do you use the `web` middleware on the routes?

**Comment by victorighalo** [comment]
> 3\. getItems

Thanks I have used the HasTaxons trait on my product model. I've updated the code to use Cart::getItems() instead, and yes, I use the Web middlleware in my controllers.

I noticed the user_id field in the cart table is null, could that be one of the problems?

**Comment by fulopattila122** [comment]
No, the user <-> cart assignment is [completely optional](https://vanilo.io/docs/0.5/cart#associating-with-users).

Is the session working properly in your application?

Eg. if you store some value, can you get the value back after page refresh?
```php
//store some data in controller
session()->put('hey', 'yo');

// ... refresh the page ...
session()->get('hey');
// Do you get 'yo' here?
```

**Comment by victorighalo** [comment]
> No, the user <-> cart assignment is [completely optional](https://vanilo.io/docs/0.5/cart#associating-with-users).
> 
> Is the session working properly in your application?
> 
> Eg. if you store some value, can you get the value back after page refresh?
> 
> ```
> //store some data in controller
> session()->put('hey', 'yo');
> 
> // ... refresh the page ...
> session()->get('hey');
> // Do you get 'yo' here?
> ```

Yes. Session works fine. I can store and retrieve the value.

**Comment by fulopattila122** [comment]
What's the value of `config('vanilo.cart.session_key')` ?
What does `session()->get(config('vanilo.cart.session_key'))` give when adding something to the cart, and after refreshing the page?

**Comment by victorighalo** [comment]
> What's the value of `config('vanilo.cart.session_key')` ?
> What does `session()->get(config('vanilo.cart.session_key'))` give when adding something to the cart, and after refreshing the page?

```
config('vanilo.cart.session_key') = null
```
when adding to cart

```
session()->get(config('vanilo.cart.session_key'))  
array (size=3)
  '_token' => string 'rPjTNEhixJYj7ZeoRAkSWUJLRTdWtvxmZ8fuLUm5' (length=40)
  '_previous' => 
    array (size=1)
      'url' => string 'http://localhost/ecommerce-laravel/public/Toyota-bus/test-product-2' (length=67)
  '_flash' => 
    array (size=2)
      'old' => 
        array (size=0)
          empty
      'new' => 
        array (size=0)
          empty
```

after adding to cart
```
session()->get(config('vanilo.cart.session_key'))
array (size=1)
  '_token' => string 'rPjTNEhixJYj7ZeoRAkSWUJLRTdWtvxmZ8fuLUm5' (length=40)
```

after second refresh

```
array (size=3)
  '_token' => string 'rPjTNEhixJYj7ZeoRAkSWUJLRTdWtvxmZ8fuLUm5' (length=40)
  '_previous' => 
    array (size=1)
      'url' => string 'http://localhost/ecommerce-laravel/public/Toyota-bus/test-product-2' (length=67)
  '_flash' => 
    array (size=2)
      'old' => 
        array (size=0)
          empty
      'new' => 
        array (size=0)
          empty
```

**Comment by fulopattila122** [comment]
`config('vanilo.cart.session_key') = null` this is the problem.

Can you post the contents of `config/concord.php` here? Do you have `config/vanilo.php` file?

**Comment by victorighalo** [comment]
My config/concrd.php file

```
<?php

return [
    'modules' => [
        Konekt\AppShell\Providers\ModuleServiceProvider::class => [
            'ui' => [
                'name' => 'Vanilo',
                'url' => '/admin/product'
            ]
        ],
        Vanilo\Framework\Providers\ModuleServiceProvider::class
    ]
];
```

I also don't have a config/vanilo.php file

**Comment by fulopattila122** [comment]
That's strange, because it looks as it should. What's the output of `var_dump(config('vanilo'))` ?

**Comment by victorighalo** [comment]
> That's strange, because it looks as it should. What's the output of `var_dump(config('vanilo'))` ?

Null

**Comment by fulopattila122** [comment]
What do `config('concord')` and `config('session')` calls return?

**Comment by victorighalo** [comment]
> What do `config('concord')` and `config('session')` calls return?

config('session') returns

```
array:15 [▼
  "driver" => "file"
  "lifetime" => "120"
  "expire_on_close" => false
  "encrypt" => false
  "files" => "C:\wamp64\www\ecommerce-laravel\storage\framework/sessions"
  "connection" => null
  "table" => "sessions"
  "store" => null
  "lottery" => array:2 [▼
    0 => 2
    1 => 100
  ]
  "cookie" => "laravel_session"
  "path" => "/"
  "domain" => null
  "secure" => false
  "http_only" => true
  "same_site" => null
]
```

config('concord')

```
array:1 [▼
  "modules" => array:2 [▼
    "Konekt\AppShell\Providers\ModuleServiceProvider" => array:1 [▼
      "ui" => array:2 [▼
        "name" => "Vanilo"
        "url" => "/admin/product"
      ]
    ]
    0 => "Vanilo\Framework\Providers\ModuleServiceProvider"
  ]
]
```

**Comment by victorighalo** [comment]
Please how can I fix this?

**Comment by fulopattila122** [comment]
Your complete vanilo config is gone. Somehow you overwrote it.
The last thing I can think of: what's the content of `vendor/vanilo/cart/src/resources/config/module/php` ?

**Comment by victorighalo** [comment]
> Your complete vanilo config is gone. Somehow you overwrote it.
> The last thing I can think of: what's the content of `vendor/vanilo/cart/src/resources/config/module/php` ?

```
return [
    'event_listeners'   => true,
    'session_key'       => 'vanilo_cart', // The session key where the cart id gets saved
    'auto_destroy'      => false, // Whether to immediately delete carts with 0 items
    'auto_assign_user'  => true, // Whether to automatically set the user_id on new carts (based on Auth::user())
    'preserve_for_user' => false, // Whether to keep and restore user carts across logins and devices
    'items'             => [
        'extra_product_attributes_to_merge' => []
    ]
];
```

**Comment by fulopattila122** [comment]
Can you maybe zip your entire project along with the `vendor/` folder (remove sensitive parts) and make it available for download?

**Comment by victorighalo** [comment]
> Can you maybe zip your entire project along with the `vendor/` folder (remove sensitive parts) and make it available for download?

https://drive.google.com/file/d/1IffV0zfohUhfYvHb7lMRoZmGxKPJB6UX/view?usp=sharing

**Comment by fulopattila122** [comment]
My OS says it's not a zip file. Please either fix it or send .tar.gz

**Comment by victorighalo** [comment]
> My OS says it's not a zip file. Please either fix it or send .tar.gz

Fixed

https://drive.google.com/file/d/1f_J89IUUR5_iLmD8r2fCYifhd4iH0DCi/view?usp=sharing

**Comment by fulopattila122** [comment]
I've checked your code. Here's what to do:

Move these 3 routes from `routes/api.php` => `routes/web.php`:
```php
Route::post('/cart/add', 'CartController@add')->name('add_to_cart');
Route::post('/cart/update/{cart_item?}', 'CartController@update')->name('update_cart');
Route::post('/cart/destroy/{cart_item?}', 'CartController@destroy')->name('destroy_cart');
```
Remove `api/cart/*` from the except array in the `App\Http\Middleware\VerifyCsrfToken` class:
```php
protected $except = [
    'api/cart/*' // <- remove
];
```
---
In general, Vanilo could do much more for you.
You're reimplementing a lots of existing Vanilo functionalities, often not in a proper way.
I suggest to re-read the [docs](https://vanilo.io/docs/0.5/installation) and study the code of the [demo app](https://github.com/vanilophp/demo).

**Comment by victorighalo** [comment]
> I've checked your code. Here's what to do:
> 
> Move these 3 routes from `routes/api.php` => `routes/web.php`:
> 
> ```
> Route::post('/cart/add', 'CartController@add')->name('add_to_cart');
> Route::post('/cart/update/{cart_item?}', 'CartController@update')->name('update_cart');
> Route::post('/cart/destroy/{cart_item?}', 'CartController@destroy')->name('destroy_cart');
> ```
> 
> Remove `api/cart/*` from the except array in the `App\Http\Middleware\VerifyCsrfToken` class:
> 
> ```
> protected $except = [
>     'api/cart/*' // <- remove
> ];
> ```
> 
> In general, Vanilo could do much more for you.
> You're reimplementing a lots of existing Vanilo functionalities, often not in a proper way.
> I suggest to re-read the [docs](https://vanilo.io/docs/0.5/installation) and study the code of the [demo app](https://github.com/vanilophp/demo).

Thanks so much. It works now. 
I'll have to take a deeper study of the Vanilo Docs so I can get things right. I will appreciate if you can point of some specific changes i can make to improve my use of Vanillo.

**Comment by fulopattila122** [comment]
> I will appreciate if you can point of some specific changes i can make to improve my use of Vanillo.

I'll do that in the coming days.
